/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.cygni.stridsberg.aoc;

import static org.junit.jupiter.api.Assertions.assertEquals;

import java.util.List;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

public class AppTest {

}
